apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
  #  - github.com/utilitywarehouse/gatekeeper-template-manifests/base?ref=1.2.4
resources:
  - delete-namespace-annotation.yaml
  - ingress-host-restriction.yaml
  - namespace-name-label-match.yaml
  - required-labels.yaml
  - taint-toleration.yaml
