apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - library/delete-annotation-requirement/template.yaml
  - library/ingress-host-restriction/template.yaml
  - library/name-label-match/template.yaml
